// packages/angular/src/lib/alert.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

export type DtAlertVariant = 'info' | 'success' | 'warning' | 'error';

@Component({
  selector: 'dt-alert',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div *ngIf="open" [class]="'dt-alert dt-alert--' + variant" role="alert">
      <div>
        <div *ngIf="title" class="dt-alert__title">{{ title }}</div>
        <div><ng-content></ng-content></div>
      </div>
      <button *ngIf="dismissible" type="button" class="dt-alert__close" aria-label="Dismiss" (click)="dismiss()">×</button>
    </div>
  `,
})
export class DtAlertComponent {
  @Input() variant: DtAlertVariant = 'info';
  @Input() title?: string;
  @Input() dismissible = false;
  @Output() dismissed = new EventEmitter<void>();
  open = true;
  dismiss() { this.open = false; this.dismissed.emit(); }
}

// packages/react/src/components/Alert.tsx
import { useState, type ReactNode } from 'react';

export type AlertVariant = 'info' | 'success' | 'warning' | 'error';

export interface AlertProps {
  variant?: AlertVariant;
  title?: string;
  dismissible?: boolean;
  onDismiss?: () => void;
  children?: ReactNode;
}

export function Alert({ variant = 'info', title, dismissible, onDismiss, children }: AlertProps) {
  const [open, setOpen] = useState(true);
  if (!open) return null;
  return (
    <div className={`dt-alert dt-alert--${variant}`} role="alert">
      <div>
        {title && <div className="dt-alert__title">{title}</div>}
        {children && <div>{children}</div>}
      </div>
      {dismissible && (
        <button
          type="button"
          className="dt-alert__close"
          aria-label="Dismiss"
          onClick={() => { setOpen(false); onDismiss?.(); }}
        >×</button>
      )}
    </div>
  );
}
