// packages/angular/src/lib/badge.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

export type DtBadgeVariant = 'success' | 'inProgress' | 'rejected' | 'submitted' | 'draft' | 'cancel';

@Component({
  selector: 'dt-badge',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<span [class]="'dt-badge dt-badge--' + variant"><ng-content></ng-content></span>`,
})
export class DtBadgeComponent {
  @Input() variant: DtBadgeVariant = 'draft';
}

// packages/react/src/components/Badge.tsx
import type { HTMLAttributes } from 'react';

export type BadgeVariant = 'success' | 'inProgress' | 'rejected' | 'submitted' | 'draft' | 'cancel';

export interface BadgeProps extends HTMLAttributes<HTMLSpanElement> {
  variant?: BadgeVariant;
}

export function Badge({ variant = 'draft', className = '', children, ...rest }: BadgeProps) {
  return (
    <span className={`dt-badge dt-badge--${variant} ${className}`.trim()} {...rest}>
      {children}
    </span>
  );
}
