// packages/angular/src/lib/breadcrumb.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

export interface DtBreadcrumbItem { label: string; href?: string; }

@Component({
  selector: 'dt-breadcrumb',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <nav class="dt-breadcrumb" aria-label="Breadcrumb">
      <ng-container *ngFor="let it of items; let last = last; let i = index">
        <ng-container *ngIf="last || !it.href; else linkTpl">
          <span [class.dt-breadcrumb__current]="last">{{ it.label }}</span>
        </ng-container>
        <ng-template #linkTpl><a [href]="it.href">{{ it.label }}</a></ng-template>
        <span *ngIf="!last" class="dt-breadcrumb__sep" aria-hidden="true">{{ separator }}</span>
      </ng-container>
    </nav>
  `,
})
export class DtBreadcrumbComponent {
  @Input() items: DtBreadcrumbItem[] = [];
  @Input() separator = '/';
}

// packages/react/src/components/Breadcrumb.tsx
import { Fragment } from 'react';

export interface BreadcrumbItem { label: string; href?: string; }

export interface BreadcrumbProps {
  items: BreadcrumbItem[];
  separator?: string;
}

export function Breadcrumb({ items, separator = '/' }: BreadcrumbProps) {
  return (
    <nav className="dt-breadcrumb" aria-label="Breadcrumb">
      {items.map((it, i) => {
        const last = i === items.length - 1;
        return (
          <Fragment key={i}>
            {last || !it.href
              ? <span className={last ? 'dt-breadcrumb__current' : undefined}>{it.label}</span>
              : <a href={it.href}>{it.label}</a>}
            {!last && <span className="dt-breadcrumb__sep" aria-hidden>{separator}</span>}
          </Fragment>
        );
      })}
    </nav>
  );
}
