// packages/angular/src/lib/input.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

let uid = 0;

@Component({
  selector: 'dt-input',
  standalone: true,
  imports: [CommonModule, FormsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="'dt-field' + (error ? ' dt-field--error' : '')">
      <div class="dt-field__control">
        <label *ngIf="label" class="dt-field__label" [attr.for]="inputId">
          <span *ngIf="required" class="dt-field__required" aria-hidden="true">*</span>{{ label }}
        </label>
        <input
          [id]="inputId"
          [type]="type"
          [placeholder]="placeholder || ''"
          [disabled]="disabled"
          [required]="required"
          [value]="value"
          [attr.aria-invalid]="!!error"
          [class]="'dt-input dt-input--' + size + (error ? ' dt-input--error' : '')"
          (input)="onInput($any($event.target).value)"
        />
      </div>
      <span *ngIf="error" class="dt-field__error">{{ error }}</span>
      <span *ngIf="!error && hint" class="dt-field__hint">{{ hint }}</span>
    </div>
  `,
})
export class DtInputComponent {
  @Input() label?: string;
  @Input() hint?: string;
  @Input() error?: string;
  @Input() placeholder?: string;
  @Input() disabled = false;
  @Input() required = false;
  @Input() type: 'text' | 'email' | 'password' | 'number' | 'tel' | 'url' = 'text';
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() value: string | number = '';
  @Output() valueChange = new EventEmitter<string>();

  inputId = `dt-input-${++uid}`;

  onInput(v: string) {
    this.value = v;
    this.valueChange.emit(v);
  }
}

// packages/react/src/components/Input.tsx
import { useId, type InputHTMLAttributes } from 'react';

export interface InputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'size'> {
  label?: string;
  hint?: string;
  error?: string;
  required?: boolean;
  size?: 'sm' | 'md' | 'lg';
}

export function Input({ label, hint, error, required, size = 'md', id, className = '', ...rest }: InputProps) {
  const reactId = useId();
  const inputId = id ?? reactId;
  const cls = `dt-input dt-input--${size} ${error ? 'dt-input--error' : ''} ${className}`.trim();
  return (
    <div className={`dt-field ${error ? 'dt-field--error' : ''}`.trim()}>
      <div className="dt-field__control">
        {label && (
          <label className="dt-field__label" htmlFor={inputId}>
            {required && <span className="dt-field__required" aria-hidden>*</span>}
            {label}
          </label>
        )}
        <input id={inputId} className={cls} required={required} aria-invalid={!!error} {...rest} />
      </div>
      {error ? <span className="dt-field__error">{error}</span> : hint ? <span className="dt-field__hint">{hint}</span> : null}
    </div>
  );
}
