// packages/react/src/components/Select.tsx
import { useId, type SelectHTMLAttributes } from 'react';

export interface SelectOption { label: string; value: string | number; disabled?: boolean; }

export interface SelectProps extends Omit<SelectHTMLAttributes<HTMLSelectElement>, 'size'> {
  label?: string;
  hint?: string;
  error?: string;
  options: SelectOption[];
  placeholder?: string;
  required?: boolean;
  size?: 'sm' | 'md' | 'lg';
}

export function Select({ label, hint, error, options, placeholder, required, size = 'md', id, className = '', ...rest }: SelectProps) {
  const reactId = useId();
  const selectId = id ?? reactId;
  const cls = `dt-select dt-input--${size} ${error ? 'dt-select--error' : ''} ${className}`.trim();
  return (
    <div className={`dt-field ${error ? 'dt-field--error' : ''}`.trim()}>
      <div className="dt-field__control">
        {label && (
          <label className="dt-field__label" htmlFor={selectId}>
            {required && <span className="dt-field__required" aria-hidden>*</span>}
            {label}
          </label>
        )}
        <select id={selectId} className={cls} required={required} aria-invalid={!!error} {...rest}>
          {placeholder && <option value="" disabled>{placeholder}</option>}
          {options.map((o) => (
            <option key={o.value} value={o.value} disabled={o.disabled}>{o.label}</option>
          ))}
        </select>
      </div>
      {error ? <span className="dt-field__error">{error}</span> : hint ? <span className="dt-field__hint">{hint}</span> : null}
    </div>
  );
}

// packages/angular/src/lib/select.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

export interface DtSelectOption { label: string; value: string | number; disabled?: boolean; }

let uid = 0;

@Component({
  selector: 'dt-select',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="dt-field">
      <label *ngIf="label" class="dt-field__label" [attr.for]="selectId">{{ label }}</label>
      <select
        [id]="selectId"
        [disabled]="disabled"
        [attr.aria-invalid]="!!error"
        [class]="'dt-select dt-input--' + size + (error ? ' dt-select--error' : '')"
        (change)="onChange($any($event.target).value)"
      >
        <option *ngIf="placeholder" value="" disabled [selected]="value === ''">{{ placeholder }}</option>
        <option *ngFor="let o of options" [value]="o.value" [disabled]="!!o.disabled" [selected]="o.value === value">{{ o.label }}</option>
      </select>
      <span *ngIf="error" class="dt-field__error">{{ error }}</span>
      <span *ngIf="!error && hint" class="dt-field__hint">{{ hint }}</span>
    </div>
  `,
})
export class DtSelectComponent {
  @Input() label?: string;
  @Input() hint?: string;
  @Input() error?: string;
  @Input() placeholder?: string;
  @Input() disabled = false;
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() options: DtSelectOption[] = [];
  @Input() value: string | number = '';
  @Output() valueChange = new EventEmitter<string>();

  selectId = `dt-select-${++uid}`;

  onChange(v: string) {
    this.value = v;
    this.valueChange.emit(v);
  }
}
