// packages/react/src/components/Tabs.tsx
import { useState, type ReactNode } from 'react';

export interface TabItem { id: string; label: string; content: ReactNode; disabled?: boolean; }

export interface TabsProps {
  items: TabItem[];
  activeId?: string;
  onChange?: (id: string) => void;
}

export function Tabs({ items, activeId, onChange }: TabsProps) {
  const [internal, setInternal] = useState(activeId ?? items[0]?.id);
  const current = activeId ?? internal;
  const select = (id: string) => { setInternal(id); onChange?.(id); };
  const active = items.find((i) => i.id === current);
  return (
    <div className="dt-tabs">
      <div className="dt-tabs__list" role="tablist">
        {items.map((it) => (
          <button
            key={it.id}
            role="tab"
            aria-selected={it.id === current}
            disabled={it.disabled}
            className={`dt-tabs__tab ${it.id === current ? 'dt-tabs__tab--active' : ''}`}
            onClick={() => select(it.id)}
          >{it.label}</button>
        ))}
      </div>
      <div className="dt-tabs__panel" role="tabpanel">{active?.content}</div>
    </div>
  );
}

// packages/angular/src/lib/tabs.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output, TemplateRef } from '@angular/core';
import { CommonModule } from '@angular/common';

export interface DtTabItem { id: string; label: string; content?: TemplateRef<unknown> | string; disabled?: boolean; }

@Component({
  selector: 'dt-tabs',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="dt-tabs">
      <div class="dt-tabs__list" role="tablist">
        <button
          *ngFor="let it of items"
          role="tab"
          [attr.aria-selected]="it.id === activeId"
          [disabled]="!!it.disabled"
          [class]="'dt-tabs__tab' + (it.id === activeId ? ' dt-tabs__tab--active' : '')"
          (click)="select(it.id)"
        >{{ it.label }}</button>
      </div>
      <div class="dt-tabs__panel" role="tabpanel">
        <ng-container *ngIf="active() as a">
          <ng-container *ngIf="isString(a.content); else tpl">{{ a.content }}</ng-container>
          <ng-template #tpl>
            <ng-container *ngTemplateOutlet="$any(a.content)"></ng-container>
          </ng-template>
        </ng-container>
      </div>
    </div>
  `,
})
export class DtTabsComponent {
  @Input() items: DtTabItem[] = [];
  @Input() activeId?: string;
  @Output() activeIdChange = new EventEmitter<string>();

  ngOnInit() { if (!this.activeId && this.items[0]) this.activeId = this.items[0].id; }
  select(id: string) { this.activeId = id; this.activeIdChange.emit(id); }
  active() { return this.items.find((i) => i.id === this.activeId); }
  isString(v: unknown): v is string { return typeof v === 'string'; }
}
